DROP DATABASE IF EXISTS ASSAABLOY;
CREATE DATABASE IF NOT EXISTS ASSAABLOY;
USE ASSAABLOY;

CREATE TABLE CLIENTES(
	IDCLIENTE     INT 							  AUTO_INCREMENT,
	CIF 		     CHAR(9)						  NOT NULL,
	IBAN		 	  CHAR(29)                   NOT NULL,
	NOMBREEMPRESA VARCHAR(50)                NOT NULL,
	DIRECCION	  VARCHAR(100),
	MAIL			  VARCHAR(40),
	FAX			  VARCHAR(10),
	CONSTRAINT	  PK_CLIENTES					  PRIMARY KEY  (IDCLIENTE),
	CONSTRAINT 	  AK_CLIENTES_CIF  			  UNIQUE 		(CIF),
	CONSTRAINT 	  AK_CLIENTES_IBAN  			  UNIQUE 		(IBAN),
	CONSTRAINT 	  AK_CLIENTES_NOMBREEMPRESA  UNIQUE 		(NOMBREEMPRESA)
);
CREATE TABLE PUERTAS(
	IDPUERTA		  		INT 	      AUTO_INCREMENT,
	NUMEROSERIE			VARCHAR(10) NOT NULL,
	IDCLIENTE	  		INT			NOT NULL,
	PUERTA		  		VARCHAR(10) NOT NULL,
	FECHAADQUISICION	DATE			NOT NULL,
	COLOR					CHAR(6)		DEFAULT 'FFFFFF' NOT NULL,
	DIMENSIONA			DOUBLE(5, 2),
	ESMOTORIZADA		BOOLEAN     DEFAULT 1,
	CONSTRAINT			PK_PUERTA				  PRIMARY KEY (IDPUERTA),
	CONSTRAINT			AK_PUERTAS_NUMEROSERIE UNIQUE		  (NUMEROSERIE),
	CONSTRAINT			FK_PUERTA_CLIENTE		  FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTES (IDCLIENTE),
	CONSTRAINT 			CK_DIMENSIONA			  CHECK (DIMENSIONA > 0),
	CONSTRAINT 			CK_COLOR					  CHECK (COLOR REGEXP '[a-fA-F0-9]{6}'),
	CONSTRAINT 			ENUM_PUERTA	           CHECK (UPPER(PUERTA) IN ('BASCULADA', 'BATIENTE', 'CORREDERA', 'ARTICULADA', 'MEGADOOR', 'RAPIDA', 'SECCIONAL'))
);
CREATE TABLE PROVEEDORES(
	IDPROVEEDOR			INT	AUTO_INCREMENT,
	NOMBRE				VARCHAR(100)	NOT NULL,
	MAIL			  		VARCHAR(40),
	FAX			 		VARCHAR(10),		
	DIRECCION			VARCHAR(100)   NOT NULL,
	CONSTRAINT 			PK_PROVEEDOR			  PRIMARY KEY (IDPROVEEDOR)		
);
CREATE TABLE TELEFONOS(
	IDTELF				INT	AUTO_INCREMENT,
	NUMTELF			   BIGINT   NOT NULL, -- TIENE 12 CIFRAS
	IDCLIENTE			INT,
	IDPROVEEDOR			INT,
	ALIAS					VARCHAR(30),
	CONSTRAINT 			PK_TELEFONO 			  PRIMARY KEY (IDTELF),
	CONSTRAINT 			AK_TELEFONO_NUMTELF    UNIQUE		  (NUMTELF),
	CONSTRAINT 			FK_TELEFONO_CLIENTE	  FOREIGN KEY (IDCLIENTE)   REFERENCES CLIENTES    (IDCLIENTE),
	CONSTRAINT			FK_TELEFONO_PROVEEDOR  FOREIGN KEY (IDPROVEEDOR) REFERENCES PROVEEDORES (IDPROVEEDOR),
	CONSTRAINT 			CK_TELEFONO				  CHECK (NUMTELF BETWEEN 10000000000 AND 999999999999)
);
CREATE TABLE MATERIALES(
	IDMATERIAL		  INT 	AUTO_INCREMENT,
	IDPROVEEDOR		  INT    NOT NULL,
	TIPO				  VARCHAR(50)  NOT NULL,
	PRECIOUNITARIO	  DOUBLE(6,2)	DEFAULT 10.00 NOT NULL,
	TAMANIO			  DOUBLE(6,2)  DEFAULT 20.00 NOT NULL, -- EN METROS CUADRADOS
	STOCK				  INT				DEFAULT 15    NOT NULL,
	CONSTRAINT 			PK_MATERIAL 			  PRIMARY KEY (IDMATERIAL),
	CONSTRAINT			FK_MATERIAL_PROVEEDOR  FOREIGN KEY (IDPROVEEDOR) REFERENCES PROVEEDORES (IDPROVEEDOR),
	CONSTRAINT			CK_PRECIOUNITARIO		  CHECK(PRECIOUNITARIO > 0),
	CONSTRAINT			CK_TAMANIO		  CHECK(TAMANIO > 0),
	CONSTRAINT			CK_STOCK		  CHECK(STOCK > 10)
);
CREATE TABLE ALMACENES(
	IDALMACEN		  INT   					  AUTO_INCREMENT,
	ESPACIOTOTAL     DOUBLE(7,3)			  DEFAULT 1000.00,
	CONSTRAINT 			PK_ALMACEN			  PRIMARY KEY (IDALMACEN),
	CONSTRAINT			CK_ESPACIOTOTAL	  CHECK(ESPACIOTOTAL > 0)
);
CREATE TABLE MATERIALESALMACENES(
	IDMATERIALALMACEN		  INT 	AUTO_INCREMENT,
	IDMATERIAL		  		  INT,
	IDALMACEN		  		  INT,
	CONSTRAINT 			PK_MATERIALALMACEN		  		  PRIMARY KEY (IDMATERIALALMACEN),
	CONSTRAINT 			AK_MATERIALALMACEN   	  		  UNIQUE		  (IDMATERIAL, IDALMACEN),
	CONSTRAINT 			FK_MATERIALALMACEN_MATERIAL	  	  FOREIGN KEY (IDMATERIAL)   REFERENCES  MATERIALES   (IDMATERIAL),
	CONSTRAINT 			FK_MATERIALALMACEN_ALMACEN		  FOREIGN KEY (IDALMACEN)    REFERENCES  ALMACENES   (IDALMACEN)
);
CREATE TABLE MATERIALESPUERTAS(
	IDMATERIALPUERTA		  INT 	AUTO_INCREMENT,
	IDPUERTA		  		  	  INT,
	IDMATERIAL		  		  INT		NOT NULL,
	CONSTRAINT 			PK_MATERIALPUERTA			  		  PRIMARY KEY (IDMATERIALPUERTA),
	CONSTRAINT 			AK_MATERIALPUERTA    	  		  UNIQUE		  (IDMATERIAL, IDPUERTA),
	CONSTRAINT 			FK_MATERIALPUERTA_PUERTA	  	  FOREIGN KEY (IDMATERIAL)   REFERENCES  MATERIALES   (IDMATERIAL),
	CONSTRAINT 			FK_MATERIALPUERTA_ALMACEN		  FOREIGN KEY (IDPUERTA)    REFERENCES   PUERTAS   (IDPUERTA)
);
CREATE TABLE GARANTIAS(
	IDGARANTIA				INT		AUTO_INCREMENT,
	IDPUERTA					INT		NOT NULL,
	MOTIVOANUL				VARCHAR(100),
	FECHAANUL				DATE     DEFAULT DATE_ADD(NOW(), INTERVAL 1 YEAR),
	FECHAINICIO				DATE		DEFAULT NOW(),
	CONSTRAINT 			PK_GARANTIA			  		  PRIMARY KEY (IDGARANTIA),
	CONSTRAINT			FK_GARANTIA_PUERTA		  FOREIGN KEY (IDPUERTA) REFERENCES PUERTAS (IDPUERTA)
);
CREATE TABLE EMPLEADOS(
	IDEMPLEADO				INT			   AUTO_INCREMENT,
	NOMBRE					VARCHAR(100)	NOT NULL,
	APELLIDOS				VARCHAR(100)	NOT NULL,
	EMPLEADO					VARCHAR(10)		NOT NULL,
	TELEFONO					BIGINT, -- CON 12 CIFRAS
	CONSTRAINT 			PK_EMPLEADO	  		  PRIMARY KEY (IDEMPLEADO),
	CONSTRAINT 			ENUM_EMPLEADO		  CHECK(UPPER(EMPLEADO) IN ('TECNICO', 'PEON')),
	CONSTRAINT 			CK_TELEFONO				  CHECK (TELEFONO BETWEEN 10000000000 AND 999999999999)				
);
CREATE TABLE PUERTASEMPLEADOS(
	IDPUERTAEMPLEADO	   INT		AUTO_INCREMENT,
	IDPUERTA					INT		NOT NULL,
	IDEMPLEADO				INT		NOT NULL,
	CONSTRAINT 			PK_PUERTAEMPLEADO	  		  	  PRIMARY KEY (IDPUERTAEMPLEADO),
	CONSTRAINT 			AK_PUERTAEMPLEADO    	  	  UNIQUE		  (IDPUERTA, IDEMPLEADO),
	CONSTRAINT 			FK_PUERTAEMPLEADO_PUERTA	  FOREIGN KEY (IDPUERTA) REFERENCES PUERTAS (IDPUERTA),
	CONSTRAINT 			FK_PUERTAEMPLEADO_EMPLEADO	  FOREIGN KEY (IDEMPLEADO) REFERENCES EMPLEADOS (IDEMPLEADO)
);
CREATE TABLE MANTENIMIENTOS(
	IDMANTENIMIENTO		INT		AUTO_INCREMENT,
	DESCRIPCION				VARCHAR(100),
	FECHAINI					DATE		NOT NULL DEFAULT NOW(),
	FECHAFIN					DATE,
	CONSTRAINT 			PK_IDMANTENIMIENTO	  		  PRIMARY KEY (IDMANTENIMIENTO)
);
CREATE TABLE MANTENIMIENTOSEMPLEADOS(
	IDMANTENIMIENTOEMPLEADO	   INT		AUTO_INCREMENT,
	IDMANTENIMIENTO				INT		NOT NULL,
	IDEMPLEADO						INT		NOT NULL,
	CONSTRAINT 			PK_MANTENIMIENTOEMPLEADO	  		  PRIMARY KEY (IDMANTENIMIENTOEMPLEADO),
	CONSTRAINT 			AK_MANTENIMIENTOEMPLEADO    	  	  		  UNIQUE		  (IDMANTENIMIENTO, IDEMPLEADO),
	CONSTRAINT 			FK_MANTENIMIENTOEMPLEADO_MANTENIMIENTO	  FOREIGN KEY (IDMANTENIMIENTO) REFERENCES MANTENIMIENTOS (IDMANTENIMIENTO),
	CONSTRAINT 			FK_MANTENIMIENTOEMPLEADO_EMPLEADO	  	     FOREIGN KEY (IDEMPLEADO) REFERENCES EMPLEADOS (IDEMPLEADO)
);
CREATE TABLE FACTURAS(
	IDFACTURA			INT 	AUTO_INCREMENT,
	IDMANTENIMIENTO	INT,
	PRECIOTOTAL			DOUBLE(6,2)	DEFAULT 0,
	COBRO					DOUBLE(6,2)	DEFAULT 0,
	CONSTRAINT 			PK_FACTURA	  		  			PRIMARY KEY (IDFACTURA),
	CONSTRAINT 			FK_FACTURA_MANTENIMIENTO   FOREIGN KEY (IDMANTENIMIENTO) REFERENCES MANTENIMIENTOS (IDMANTENIMIENTO),
	CONSTRAINT			CK_PRECIOTOTAL		  CHECK(PRECIOTOTAL >= 0)
);
